# Generated by Django 4.2.4 on 2023-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uom', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('avg_price', models.FloatField(default=0.0, help_text='USD. (unknown price will stay at $0.00)')),
            ],
        ),
    ]
