# Generated by Django 4.2.4 on 2023-08-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
