# Generated by Django 4.2.4 on 2023-08-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_remove_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='avg_price',
        ),
    ]
