# Generated by Django 4.2.4 on 2023-08-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_remove_ingredient_avg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='uom',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
