# Generated by Django 4.2.4 on 2023-08-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_alter_ingredient_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='uom',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
