# Generated by Django 4.2.4 on 2023-08-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_alter_ingredient_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='uom',
            field=models.CharField(blank=True, choices=[('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('clove', 'Clove'), ('slice', 'Slice'), ('oz', 'Ounce'), ('g', 'Gram'), ('pc', 'Piece'), ('half', 'Half'), ('bag', 'Bag'), ('cup', 'Cup'), ('wedge', 'Wedge'), ('pinch', 'Pinch')], default=None, max_length=20),
        ),
    ]
