# Generated by Django 4.2.4 on 2023-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_alter_ingredient_uom'),
        ('recipes', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='ingredients.ingredient'),
        ),
    ]
